### ISSUE TITLE
Unable to install package weconnect==0.54.1

### ISSUE THREAD

**Issue by MarSlz** [mitch-dc/volkswagen_we_connect_id#154]
## Version of the custom_component
Home Assistant 2023.3.0
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230301.0 - latest
Volkswagen We Connect ID 
v0.1.4

## Installation method (hacs / manual)
hacs

## Describe the bug

Error Message when adding the Integration (before LogIn Window open):
"Der Konfigurationsfluss konnte nicht geladen werden: 500 Internal Server Error Server got itself in trouble"

Log:
2023-03-02 18:14:10.743 ERROR (SyncWorker_7) [homeassistant.util.package] Unable to install package weconnect==0.54.1: ERROR: Cannot install weconnect==0.54.1 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by Monotono** [comment]
Got the same Problem. Here is my Log, maybe it helps aswell

Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 20:15:51 (3 occurrences)
Last logged: 20:15:58

Unable to install package weconnect==0.54.1: ERROR: Cannot install weconnect==0.54.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

**Comment by tsg21** [comment]
Possibly the same issue as we have seen before. The requests library required by the weconnect library conflicts with the one provided/mandated by homeassistant.

**Comment by robinostlund** [comment]
Upgrade to HA 2023.3.1, but we are pending this pull request also #155 once that is merged and released it will be working but it requires HA 2023.3.1
