### ISSUE TITLE
To long names

### ISSUE THREAD

**Issue by gkrallo** [mitch-dc/volkswagen_we_connect_id#21]
The user interface in HA don’t seem to support that long parameter name
Might not be some nice to change now due to all that use this but I think 
"vw_id_3_charge_rate" had been enough compare to  “sensor.volkswagen_id_id_3_pro_performance_charge_rate”,  7 instead of 34 characters as an identifier that should have make it easier to find the right parameter in many of the graphical interfaces

  - entity: sensor.volkswagen_id_id_3_pro_performance_charge_rate
  - entity: sensor.volkswagen_id_id_3_pro_performance_charge_type

<img width="315" alt="image" src="https://user-images.githubusercontent.com/96731141/157870099-8be61fa6-6c91-4aca-a7ab-3caeb5c57cd8.png">

**Comment by mitch-dc** [comment]
You car's name is very long ;). I use the nickname of the car to for the entity names. So if you have multiple id cars you dont get sensors with _2

**Comment by Maxi531** [comment]
I don't think this is a problem many people will have, as one would have to have two identical cars, for it to be "_2" at the end. Being able to name the car in HA while setting up the integration, would be a solution to the problem.

**Comment by sunnyd24** [comment]
> I use the nickname of the car to for the entity names. So if you have multiple id cars you dont get sensors with _2

@mitch-dc Good work here, very interesting and useful integration, thanks!

I would second being able to "nickname" car at initial integration setup, rather than by default being "volkswagen_id_vw_id_X_vwXXXX2XXX00000X_variable" which makes the initial card too long to read variable.

I had to manually rename each entity and add a more useful and meaningful name to each entity for easy reading.

**Comment by mitch-dc** [comment]
https://github.com/mitch-dc/volkswagen_we_connect_id/releases/tag/v0.0.9
