### ISSUE TITLE
Add dependency warning to change log

### ISSUE THREAD

**Issue by JelleKoster** [mitch-dc/volkswagen_we_connect_id#44]
## Installation method (hacs / manual)
Hacs

## Installation method of hass (venv, docker, hassio,...)
HA OS

## Describe the bug

Note the solution for #37 caused errors for me after updating this volkswagen_we_connect_id integration.

I'm using HA OS, and I was a few major versions behind on HA core. (2022.3.8)

````
Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: July 8, 2022 at 9:25:21 PM (3 occurrences)
Last logged: July 8, 2022 at 9:26:46 PM

Unable to install package weconnect==0.44.2: ERROR: Cannot install weconnect==0.44.2 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts WARNING: You are using pip version 22.0.3; however, version 22.1.2 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
````

In the HA core 2022.7.0 release notes (available 3 days ago...) I recall reading they bumped the python version.
I suspect this is the cause of the above error, and upgrading HA did resolve the issue.

Is it possible to update the change log of this component retroactively?
If so and if it's confirmed the python (or HA) upgrade is a dependency, it would be appropriate to add a dependency warning. (to only update this component if on HA 2022.7.1 or if the user manually updates python to 3.10)

**Comment by tsg21** [comment]
I _think_ the problem is that in HA 2022.7.0 they bumped the version of `requests` which is bundled with the core, and you are not supposed to include dependencies on that library in integrations:

https://developers.home-assistant.io/docs/creating_integration_manifest/#custom-integration-requirements

> Custom integrations should only include requirements that are not required by the Core [requirements.txt](https://github.com/home-assistant/core/blob/dev/requirements.txt).

This integration depends on an upstream library [WeConnect-python](https://github.com/tillsteinbach/WeConnect-python) which itself has a dependency on `requests` specified.

https://github.com/tillsteinbach/WeConnect-python/blob/main/requirements.txt

This seems pretty legitimate - the upstream library is has no awareness of this integration and nor should it. However if these dependencies conflict, then this integration breaks.

I'm not sure what the solution is here. Perhaps we could ask tillsteinbach to accept more versions of requests, or not update it so enthusiastically?

I'm not sure this completely adds up though. It seems like the dependencies should have been compatible.

**Comment by mitch-dc** [comment]
We had to bump te weconnect version so it works with the later versions of HA. 
https://github.com/mitch-dc/volkswagen_we_connect_id/issues/39

I will add a line to the readme, for now just update HA :)
